# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fec80532f7462b4f11f5b86a026d48ba9b8c9c2641e866290c68263289a6f3bae4d733b411a8b4d8684f1c35cc8d4499f05af10d5f7923fa1e377022dc5be81a

test:
  secret_key_base: 1c89723c361b24af9284b2f5dbd26f556a47874d56776807b0350b7b574d21f4d5254c059550769bb3e7260f562f9b4331e26bbb7c3e5bb7814f4dda8b7639a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
